workflows:
  ios-app-store-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic21
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.loveuad.carecircle
      vars:
        TEAM_ID: "7PA725G59N"
        BUNDLE_ID: "com.loveuad.carecircle"
        XCODE_PROJECT: "src/LoveUAD.xcodeproj"
        XCODE_SCHEME: "LoveUAD"
        APP_NAME: "LoveUAD"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Install CocoaPods
        script: |
          if [ -f "src/Podfile" ]; then
            cd src
            pod install
          fi
      - name: Set bundle identifier
        script: |
          cd src
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "LoveUAD/Info.plist" || true
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - kanchan.g12@gmail.com
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
        submit_to_app_store: false
